- name: install rsyslog
  yum:
    name: rsyslog

- name: copy logfile
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf

- name: create supervisor config
  copy:
    src: syslog.ini
    dest: /etc/supervisord.d/syslog.ini
  register: supervisord

- name: reload supervisord
  shell: supervisorctl reload
  when: supervisord.changed
