- name: install rsyslog
  yum:
    name: rsyslog

- name: copy logfile
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
- name: remove listen.conf
  file:
    path: /etc/rsyslog.d/listen.conf
    state: absent

- name: create supervisor config
  copy:
    src: syslog.ini
    dest: /etc/supervisord.d/syslog.ini
  register: supervisor

- name: start syslog
  supervisorctl:
    name: syslog
    state: started

- name: reload supervisor
  supervisorctl:
    name: syslog
    state: restarted
  when: supervisor.changed
