- name: install rsyslog
  yum:
    name: rsyslog

- name: copy logfile
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf

- name: create supervisor config
  copy:
    src: syslog.ini
    dest: /etc/supervisord.d/syslog.ini
  register: supervisor

- name: reload supervisor
  supervisorctl:
    name: syslog
    state: restarted
  when: supervisor.changed
